name: Build Step

on:
  push:
    branches: ['master']

jobs:
  build-and-push-registry:
    name: Build and push to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}
      
      - name: Build image and push to Docker Hub and GitHub Container registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            rose13/python-test:${{ github.sha }}
            ghcr.io/ngocvinhvu/python-test:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/master' }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-registry']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ngocvinhvu/test-kpack
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "vungocvinh95@gmail.com"
          git config --global user.name "ngocvinhvu"
          echo ${{ github.sha }}
          sed -i "s#${{ github.actor }}.*#${{ github.actor }}/argocd-test:${{ github.sha }}#g" deployment.yaml
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin master  